# Local docker-compose for developing
version: "3.5"
services:
    bing:
        container_name: bing-mysite-runserver
        command: m runserver 0.0.0.0:8080
        restart: always
        depends_on:
            - dynamodb
        ports:
            - 8080:8080
        env_file: ./mysite/env.local.runserver
        volumes:
            - .:/usr/src/app

    dynamodb:
        image: amazon/dynamodb-local:latest
        container_name: bing_dynamodb
        ports:
            - 8000:8000
        working_dir: /home/dynamodblocal
        command:
            [
                "-jar",
                "DynamoDBLocal.jar",
                "-sharedDb",
                "-dbPath",
                "/home/dynamodblocal",
            ]
        volumes:
            - dynamodb_data:/home/dynamodblocal

volumes:
    dynamodb_data:
